### ISSUE TITLE
Metagon.cf resolves to suspicious site in farsi or arabic

### ISSUE THREAD

**Issue by anoduck** [austinhuang0131/metagon#10]
* Platform: Linux 64
* Category: Question

## Description
When I went to visit the documentation for this project. The url resolved to a suspicious site that was in farsi or arabic. Thought this was suspicious since, the project appears to have been written in english.

<a href="https://ibb.co/vBtJRtm"><img src="https://i.ibb.co/vBtJRtm/Screenshot-2020-02-23.png" alt="Screenshot-2020-02-23" border="0"></a>

### Steps to Reproduce
Open metagon.cf in browser

**Comment by austinhuang0131** [comment]
Freenom took over the domain without my consent (I did renew it then)...

I thought I changed every link except botlist.co (requires payment)... Well I just did. The correct link has been https://metagon.austinhuang.me for like a year. (Also this project is pretty much no longer maintained since it's just too much work for myself, if you wanna join then sure)

**Comment by anoduck** [comment]
Ok, Cool...
You need to change the link at the bottom of your `readme.md` file. It still points to https://metagon.cf and is how I wound up there.
I am really just looking for a way to access KIK from my computer, the bot idea was probably not my best solution.

**Comment by anoduck** [comment]
Oops, forgot to close this one out.  Thanks for doing it for me.
